- name: prepare install for ansible
  apt: name={{item}} state=present
  with_items:
    - software-properties-common
    - aptitude
- name: update & upgrade
  apt: update_cache=yes upgrade=safe
- name: prepare install ruby   
  apt: name={{item}} state=present
  with_items:
    - git
    - build-essential
    - libssl-dev

  
